name: GitHub-Profile-3D-Contrib

on:
  schedule: # 매일 오전 3시 KST
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      - uses: yoshi389111/github-profile-3d-contrib@0.6.1
        with:
          user_name: SuKyeong2002
          svg_path: ./profile-3d-contrib/profile-3d-full.svg
          animation: true
          chart: true
          color: "rainbow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name "SuKyeong2002"
          git config user.email "osukyeong0109@gmail.com"
          git add -A .
          git commit -m "generated"
          git push
